export interface ObjectDetectionClass {
    name: string;
}

export const CLASSES: { [key: string]: ObjectDetectionClass } = {
    0: { name: "person" },
    1: { name: "bicycle" },
    2: { name: "car" },
    3: { name: "motorcycle" },
    4: { name: "airplane" },
    5: { name: "bus" },
    6: { name: "train" },
    7: { name: "truck" },
    8: { name: "boat" },
    9: { name: "traffic light" },
    10: { name: "fire hydrant" },
    11: { name: "stop sign" },
    12: { name: "parking meter" },
    13: { name: "bench" },
    14: { name: "bird" },
    15: { name: "cat" },
    16: { name: "dog" },
    17: { name: "horse" },
    18: { name: "sheep" },
    19: { name: "cow" },
    20: { name: "elephant" },
    21: { name: "bear" },
    22: { name: "zebra" },
    23: { name: "giraffe" },
    24: { name: "backpack" },
    25: { name: "umbrella" },
    26: { name: "handbag" },
    27: { name: "tie" },
    28: { name: "suitcase" },
    29: { name: "frisbee" },
    30: { name: "skis" },
    31: { name: "snowboard" },
    32: { name: "sports ball" },
    33: { name: "kite" },
    34: { name: "baseball bat" },
    35: { name: "baseball glove" },
    36: { name: "skateboard" },
    37: { name: "surfboard" },
    38: { name: "tennis racket" },
    39: { name: "bottle" },
    40: { name: "wine glass" },
    41: { name: "cup" },
    42: { name: "fork" },
    43: { name: "knife" },
    44: { name: "spoon" },
    45: { name: "bowl" },
    46: { name: "banana" },
    47: { name: "apple" },
    48: { name: "sandwich" },
    49: { name: "orange" },
    50: { name: "broccoli" },
    51: { name: "carrot" },
    52: { name: "hot dog" },
    53: { name: "pizza" },
    54: { name: "donut" },
    55: { name: "cake" },
    56: { name: "chair" },
    57: { name: "couch" },
    58: { name: "potted plant" },
    59: { name: "bed" },
    60: { name: "dining table" },
    61: { name: "toilet" },
    62: { name: "tv" },
    63: { name: "laptop" },
    64: { name: "mouse" },
    65: { name: "remote" },
    66: { name: "keyboard" },
    67: { name: "cell phone" },
    68: { name: "microwave" },
    69: { name: "oven" },
    70: { name: "toaster" },
    71: { name: "sink" },
    72: { name: "refrigerator" },
    73: { name: "book" },
    74: { name: "clock" },
    75: { name: "vase" },
    76: { name: "scissors" },
    77: { name: "teddy bear" },
    78: { name: "hair drier" },
    79: { name: "toothbrush" },
};
